/**
 * Autogenerated by Thrift Compiler (0.13.0)
 * <p>
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package com.chxlay.thrift.generate;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class ThriftDataConstants {

    public static final int INT32CONSTANT = 9853;

    public static final java.util.Map<java.lang.String, java.lang.String> MAPCONSTANT = new java.util.HashMap<java.lang.String, java.lang.String>();

    static {
        MAPCONSTANT.put("k1", "v1");
        MAPCONSTANT.put("k2", "v2");
    }

    public static final java.util.Set<java.lang.String> FANS = new java.util.HashSet<java.lang.String>();

    static {
        FANS.add("user1");
        FANS.add("user2");
    }

    public static final java.util.List<java.lang.String> NAMES_LIST = new java.util.ArrayList<java.lang.String>();

    static {
        NAMES_LIST.add("Tom");
        NAMES_LIST.add("Jack");
    }

}
