// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.chxlay.grpc.protobuf;

/**
 * <pre>
 * 定义响应数据
 * </pre>
 * <p>
 * Protobuf type {@code com.chxlay.proto.ProtoResponse}
 */
public final class ProtoResponse extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.chxlay.proto.ProtoResponse)
        ProtoResponseOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use ProtoResponse.newBuilder() to construct.
    private ProtoResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private ProtoResponse() {
        stuName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
        return new ProtoResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    private ProtoResponse(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 10: {
                        java.lang.String s = input.readStringRequireUtf8();

                        stuName_ = s;
                        break;
                    }
                    default: {
                        if (!parseUnknownField(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return com.chxlay.grpc.protobuf.StudentProto.internal_static_com_chxlay_proto_ProtoResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return com.chxlay.grpc.protobuf.StudentProto.internal_static_com_chxlay_proto_ProtoResponse_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.chxlay.grpc.protobuf.ProtoResponse.class, com.chxlay.grpc.protobuf.ProtoResponse.Builder.class);
    }

    public static final int STU_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object stuName_;

    /**
     * <code>string stu_name = 1;</code>
     *
     * @return The stuName.
     */
    @java.lang.Override
    public java.lang.String getStuName() {
        java.lang.Object ref = stuName_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            stuName_ = s;
            return s;
        }
    }

    /**
     * <code>string stu_name = 1;</code>
     *
     * @return The bytes for stuName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getStuNameBytes() {
        java.lang.Object ref = stuName_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            stuName_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (!getStuNameBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, stuName_);
        }
        unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getStuNameBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, stuName_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.chxlay.grpc.protobuf.ProtoResponse)) {
            return super.equals(obj);
        }
        com.chxlay.grpc.protobuf.ProtoResponse other = (com.chxlay.grpc.protobuf.ProtoResponse) obj;

        if (!getStuName()
                .equals(other.getStuName())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + STU_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getStuName().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static com.chxlay.grpc.protobuf.ProtoResponse parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.chxlay.grpc.protobuf.ProtoResponse parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.chxlay.grpc.protobuf.ProtoResponse parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.chxlay.grpc.protobuf.ProtoResponse parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.chxlay.grpc.protobuf.ProtoResponse parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.chxlay.grpc.protobuf.ProtoResponse parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.chxlay.grpc.protobuf.ProtoResponse parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static com.chxlay.grpc.protobuf.ProtoResponse parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.chxlay.grpc.protobuf.ProtoResponse parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.chxlay.grpc.protobuf.ProtoResponse parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.chxlay.grpc.protobuf.ProtoResponse parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static com.chxlay.grpc.protobuf.ProtoResponse parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.chxlay.grpc.protobuf.ProtoResponse prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * <pre>
     * 定义响应数据
     * </pre>
     * <p>
     * Protobuf type {@code com.chxlay.proto.ProtoResponse}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:com.chxlay.proto.ProtoResponse)
            com.chxlay.grpc.protobuf.ProtoResponseOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.chxlay.grpc.protobuf.StudentProto.internal_static_com_chxlay_proto_ProtoResponse_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.chxlay.grpc.protobuf.StudentProto.internal_static_com_chxlay_proto_ProtoResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.chxlay.grpc.protobuf.ProtoResponse.class, com.chxlay.grpc.protobuf.ProtoResponse.Builder.class);
        }

        // Construct using com.chxlay.grpc.protobuf.ProtoResponse.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            stuName_ = "";

            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return com.chxlay.grpc.protobuf.StudentProto.internal_static_com_chxlay_proto_ProtoResponse_descriptor;
        }

        @java.lang.Override
        public com.chxlay.grpc.protobuf.ProtoResponse getDefaultInstanceForType() {
            return com.chxlay.grpc.protobuf.ProtoResponse.getDefaultInstance();
        }

        @java.lang.Override
        public com.chxlay.grpc.protobuf.ProtoResponse build() {
            com.chxlay.grpc.protobuf.ProtoResponse result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public com.chxlay.grpc.protobuf.ProtoResponse buildPartial() {
            com.chxlay.grpc.protobuf.ProtoResponse result = new com.chxlay.grpc.protobuf.ProtoResponse(this);
            result.stuName_ = stuName_;
            onBuilt();
            return result;
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.chxlay.grpc.protobuf.ProtoResponse) {
                return mergeFrom((com.chxlay.grpc.protobuf.ProtoResponse) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.chxlay.grpc.protobuf.ProtoResponse other) {
            if (other == com.chxlay.grpc.protobuf.ProtoResponse.getDefaultInstance()) return this;
            if (!other.getStuName().isEmpty()) {
                stuName_ = other.stuName_;
                onChanged();
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            com.chxlay.grpc.protobuf.ProtoResponse parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (com.chxlay.grpc.protobuf.ProtoResponse) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private java.lang.Object stuName_ = "";

        /**
         * <code>string stu_name = 1;</code>
         *
         * @return The stuName.
         */
        @Override
        public java.lang.String getStuName() {
            java.lang.Object ref = stuName_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                stuName_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string stu_name = 1;</code>
         *
         * @return The bytes for stuName.
         */
        @Override
        public com.google.protobuf.ByteString
        getStuNameBytes() {
            java.lang.Object ref = stuName_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                stuName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string stu_name = 1;</code>
         *
         * @param value The stuName to set.
         * @return This builder for chaining.
         */
        public Builder setStuName(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            stuName_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string stu_name = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearStuName() {

            stuName_ = getDefaultInstance().getStuName();
            onChanged();
            return this;
        }

        /**
         * <code>string stu_name = 1;</code>
         *
         * @param value The bytes for stuName to set.
         * @return This builder for chaining.
         */
        public Builder setStuNameBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            stuName_ = value;
            onChanged();
            return this;
        }

        @java.lang.Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:com.chxlay.proto.ProtoResponse)
    }

    // @@protoc_insertion_point(class_scope:com.chxlay.proto.ProtoResponse)
    private static final com.chxlay.grpc.protobuf.ProtoResponse DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new com.chxlay.grpc.protobuf.ProtoResponse();
    }

    public static com.chxlay.grpc.protobuf.ProtoResponse getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProtoResponse>
            PARSER = new com.google.protobuf.AbstractParser<ProtoResponse>() {
        @java.lang.Override
        public ProtoResponse parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new ProtoResponse(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<ProtoResponse> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProtoResponse> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public com.chxlay.grpc.protobuf.ProtoResponse getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

