// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.chxlay.grpc.protobuf;

public interface ProtoRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.chxlay.proto.ProtoRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 stu_id = 1;</code>
     *
     * @return The stuId.
     */
    int getStuId();
}
