// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.chxlay.grpc.protobuf;

public interface ProtoResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.chxlay.proto.ProtoResponse)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string stu_name = 1;</code>
     *
     * @return The stuName.
     */
    java.lang.String getStuName();

    /**
     * <code>string stu_name = 1;</code>
     *
     * @return The bytes for stuName.
     */
    com.google.protobuf.ByteString
    getStuNameBytes();
}
