// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.chxlay.grpc.protobuf;

public interface RequestListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.chxlay.proto.RequestList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * repeated 表示集合
   * </pre>
   *
   * <code>repeated .com.chxlay.proto.ProtoRequest request = 1;</code>
   */
  java.util.List<com.chxlay.grpc.protobuf.ProtoRequest> 
      getRequestList();
  /**
   * <pre>
   * repeated 表示集合
   * </pre>
   *
   * <code>repeated .com.chxlay.proto.ProtoRequest request = 1;</code>
   */
  com.chxlay.grpc.protobuf.ProtoRequest getRequest(int index);
  /**
   * <pre>
   * repeated 表示集合
   * </pre>
   *
   * <code>repeated .com.chxlay.proto.ProtoRequest request = 1;</code>
   */
  int getRequestCount();
  /**
   * <pre>
   * repeated 表示集合
   * </pre>
   *
   * <code>repeated .com.chxlay.proto.ProtoRequest request = 1;</code>
   */
  java.util.List<? extends com.chxlay.grpc.protobuf.ProtoRequestOrBuilder> 
      getRequestOrBuilderList();
  /**
   * <pre>
   * repeated 表示集合
   * </pre>
   *
   * <code>repeated .com.chxlay.proto.ProtoRequest request = 1;</code>
   */
  com.chxlay.grpc.protobuf.ProtoRequestOrBuilder getRequestOrBuilder(
      int index);
}
