// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.chxlay.grpc.protobuf;

public interface ResponseListOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.chxlay.proto.ResponseList)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * repeated 表示集合
     * </pre>
     *
     * <code>repeated .com.chxlay.proto.ProtoResponse response = 1;</code>
     */
    java.util.List<com.chxlay.grpc.protobuf.ProtoResponse>
    getResponseList();

    /**
     * <pre>
     * repeated 表示集合
     * </pre>
     *
     * <code>repeated .com.chxlay.proto.ProtoResponse response = 1;</code>
     */
    com.chxlay.grpc.protobuf.ProtoResponse getResponse(int index);

    /**
     * <pre>
     * repeated 表示集合
     * </pre>
     *
     * <code>repeated .com.chxlay.proto.ProtoResponse response = 1;</code>
     */
    int getResponseCount();

    /**
     * <pre>
     * repeated 表示集合
     * </pre>
     *
     * <code>repeated .com.chxlay.proto.ProtoResponse response = 1;</code>
     */
    java.util.List<? extends com.chxlay.grpc.protobuf.ProtoResponseOrBuilder>
    getResponseOrBuilderList();

    /**
     * <pre>
     * repeated 表示集合
     * </pre>
     *
     * <code>repeated .com.chxlay.proto.ProtoResponse response = 1;</code>
     */
    com.chxlay.grpc.protobuf.ProtoResponseOrBuilder getResponseOrBuilder(
            int index);
}
