// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.chxlay.grpc.protobuf;

public interface StreamRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.chxlay.proto.StreamRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.chxlay.proto.User user = 1;</code>
     *
     * @return Whether the user field is set.
     */
    boolean hasUser();

    /**
     * <code>.com.chxlay.proto.User user = 1;</code>
     *
     * @return The user.
     */
    com.chxlay.grpc.protobuf.User getUser();

    /**
     * <code>.com.chxlay.proto.User user = 1;</code>
     */
    com.chxlay.grpc.protobuf.UserOrBuilder getUserOrBuilder();
}
