// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.chxlay.grpc.protobuf;

public final class StudentProto {
    private StudentProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_chxlay_proto_ProtoRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_chxlay_proto_ProtoRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_chxlay_proto_ProtoResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_chxlay_proto_ProtoResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\rStudent.proto\022\020com.chxlay.proto\"\036\n\014Pro" +
                        "toRequest\022\016\n\006stu_id\030\001 \001(\005\"!\n\rProtoRespon" +
                        "se\022\020\n\010stu_name\030\001 \001(\t2\367\002\n\016StudentService\022" +
                        "V\n\021GetStuNameByStuId\022\036.com.chxlay.proto." +
                        "ProtoRequest\032\037.com.chxlay.proto.ProtoRes" +
                        "ponse\"\000\022U\n\016GetAsStreamReq\022\036.com.chxlay.p" +
                        "roto.ProtoRequest\032\037.com.chxlay.proto.Pro" +
                        "toResponse\"\000(\001\022\\\n\025GetReqReturnStreamRes\022" +
                        "\036.com.chxlay.proto.ProtoRequest\032\037.com.ch" +
                        "xlay.proto.ProtoResponse\"\0000\001\022X\n\017GetBothA" +
                        "sStream\022\036.com.chxlay.proto.ProtoRequest\032" +
                        "\037.com.chxlay.proto.ProtoResponse\"\000(\0010\001B," +
                        "\n\030com.chxlay.grpc.protobufB\014StudentProto" +
                        "H\001P\001b\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_com_chxlay_proto_ProtoRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_com_chxlay_proto_ProtoRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_chxlay_proto_ProtoRequest_descriptor,
                new java.lang.String[]{"StuId",});
        internal_static_com_chxlay_proto_ProtoResponse_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_com_chxlay_proto_ProtoResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_chxlay_proto_ProtoResponse_descriptor,
                new java.lang.String[]{"StuName",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
