// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.chxlay.grpc.protobuf;

public interface UserOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.chxlay.proto.User)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     *
     * @return The id.
     */
    int getId();

    /**
     * <code>string user_name = 2;</code>
     *
     * @return The userName.
     */
    java.lang.String getUserName();

    /**
     * <code>string user_name = 2;</code>
     *
     * @return The bytes for userName.
     */
    com.google.protobuf.ByteString
    getUserNameBytes();

    /**
     * <code>string nick_name = 3;</code>
     *
     * @return The nickName.
     */
    java.lang.String getNickName();

    /**
     * <code>string nick_name = 3;</code>
     *
     * @return The bytes for nickName.
     */
    com.google.protobuf.ByteString
    getNickNameBytes();
}
